# Generated by Django 3.1 on 2022-05-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todos',
        ),
    ]
